baseURL = "https://mashfiqur05.github.io/"
languageCode = "en-us"
title = "Semicolon"
theme = "hugo-PaperMod"
paginate = 5

[params]
  author = "Mashfiqur Rahman"
  description = "A personal blog by Mashfiqur Rahman"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
